server:
  port: 9000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/hello-spring/demo;
    username : sa
    password :
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update #create update none
    properties:
      hibernate:
       show_sql: true
      #format_sql: true
    naming:
      physical-strategy:org.hibernater.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: demoApplication_v3
